/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdi.pkgfinal;

import java.awt.Color;
import javax.swing.BoundedRangeModel;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author pc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
        jFileChooser1.addChoosableFileFilter(new FileNameExtensionFilter("Imagem .pbm, .pgm, .ppm", "pgm", "pbm", "ppm"));
        jFileChooser1.removeChoosableFileFilter(jFileChooser1.getAcceptAllFileFilter());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtp = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho PDI Final");
        setPreferredSize(new java.awt.Dimension(1355, 750));

        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setMaximumSize(new java.awt.Dimension(1335, 900));
        jScrollPane4.setPreferredSize(new java.awt.Dimension(1335, 750));

        jPanel1.setMaximumSize(new java.awt.Dimension(1328, 856));
        jPanel1.setPreferredSize(new java.awt.Dimension(1328, 856));
        jPanel1.setRequestFocusEnabled(false);

        jScrollPane1.setViewportView(jLabel1);

        jScrollPane2.setViewportView(jLabel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/codigos/Double_Arrow.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("RESULTADO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("IMAGEM DE ENTRADA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Codigo Executado:");

        jScrollPane3.setViewportView(jLabel6);

        jtp.setEditable(false);
        jtp.setBackground(new java.awt.Color(204, 204, 204));
        jtp.setContentType("text/html"); // NOI18N
        jtp.setPreferredSize(new java.awt.Dimension(630, 301));
        jScrollPane5.setViewportView(jtp);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Help Text:");

        jToggleButton1.setText("Sinc SideBar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel4)
                        .addGap(239, 239, 239)
                        .addComponent(jToggleButton1)
                        .addGap(240, 240, 240)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jButton1)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Abrir Imagem");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem42.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem42.setText("Salva Como");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem42);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Reload");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setText("Fechar");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ponto a Ponto");

        jMenu3.setText("Girar");

        jMenuItem3.setText("90º Direita");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("90º Esquerda");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Espelhar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenu2.add(jMenu3);

        jMenu14.setText("Zoom");

        jMenuItem11.setText("Aumentar Img");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem11);

        jMenuItem12.setText("Diminuir Img");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem12);

        jMenu2.add(jMenu14);

        jMenuItem2.setText("Binarizacao");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem45.setText("Clarear Soma");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem45);

        jMenuItem46.setText("Clarear Multp");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem46);

        jMenuItem44.setText("Escurecer Div");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem44);

        jMenuItem47.setText("Escurecer Sub");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem47);

        jMenuItem19.setText("Correção Gama");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem41.setText("Negativo");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem41);

        jMenuItem17.setText("Somar Imagens");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem18.setText("Subtrair Imagens");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem18);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Filtragem Espacial");

        jMenuItem8.setText("Laplaciano 4");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem50.setText("Laplaciano -4");
        jMenuItem50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem50ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem50);

        jMenuItem9.setText("Laplaciano 8");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem51.setText("Laplaciano -8");
        jMenuItem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem51ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem51);

        jMenuItem10.setText("Passa Baixa");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu15.setText("Histograma");

        jMenuItem14.setText("Equalização");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem14);

        jMenuItem15.setText("Equalizacão Local");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem15);

        jMenuItem13.setText("Gravar Histograma");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem13);

        jMenuItem16.setText("Estatística por Histograma");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem16);

        jMenuBar1.add(jMenu15);

        jMenu6.setText("Canais");

        jMenu7.setText("RGB");

        jMenu9.setText("Somar");

        jMenuItem20.setText("Vermelho");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem20);

        jMenuItem21.setText("Verde");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem21);

        jMenuItem22.setText("Azul");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem22);

        jMenu7.add(jMenu9);

        jMenu10.setText("Subtrair");

        jMenuItem25.setText("Vermelho");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem25);

        jMenuItem24.setText("Verde");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem24);

        jMenuItem23.setText("Azul");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem23);

        jMenu7.add(jMenu10);

        jMenu11.setText("Misturar");

        jMenuItem35.setText("RBG");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem35);

        jMenuItem36.setText("GRB");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem36);

        jMenuItem37.setText("GBR");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem37);

        jMenuItem38.setText("BRG");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem38);

        jMenuItem39.setText("BGR");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem39);

        jMenuItem40.setText("RGB");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem40);

        jMenu7.add(jMenu11);

        jMenu12.setText("Extrair RGB");

        jMenuItem26.setText("Vermelho");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem26);

        jMenuItem27.setText("Verde");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem27);

        jMenuItem28.setText("Azul");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem28);

        jMenu7.add(jMenu12);

        jMenuItem48.setText("Composição 3 imagens");
        jMenuItem48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem48ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem48);

        jMenu6.add(jMenu7);

        jMenu8.setText("Extrair HSI");

        jMenuItem29.setText("Hue");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem29);

        jMenuItem30.setText("Saturacao");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem30);

        jMenuItem31.setText("Intensidade");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem31);

        jMenu6.add(jMenu8);

        jMenu13.setText("Extrair CMY");

        jMenuItem32.setText("Ciano");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem32);

        jMenuItem33.setText("Magenta");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem33);

        jMenuItem34.setText("Amarelo");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem34);

        jMenu6.add(jMenu13);

        jMenuItem49.setText("Pseudo Cores");
        jMenuItem49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem49);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:   ABRIR IMAGEM
        if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                img = new Imagem();
                img.carregaImagem(jFileChooser1.getSelectedFile());
                img2 = null;
                attImagem();
                attImagem2();
                attCodigo(0);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:   BINARIZACAO
        if (img != null && img.getT() == 2) {
            try {
                img2 = Transformacao.binarizacao(img, Integer.valueOf(JOptionPane.showInputDialog("Valor do Limiar: ")));
                attCodigo(1);
                attImagem2();
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here: 90º DIREITA
        if (img != null) {
            try {
                img2 = Transformacao.rotacionar90Direita(img);
                attImagem2();
                attCodigo(3);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:     ESPELHAR
        if (img != null) {
            try {
                img2 = Transformacao.espelhar(img);
                attImagem2();
                attCodigo(2);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:     90º ESQUERDA
        if (img != null) {
            try {
                img2 = Transformacao.rotacionar90Esquerda(img);
                attImagem2();
                attCodigo(4);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:  RELOAD
        if (img != null) {
            try {
                img = new Imagem();
                img.carregaImagem(jFileChooser1.getSelectedFile());
                img2 = null;
                attImagem();
                attImagem2();
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:  FILTRO LAPLACIANO1
        if (img != null) {
            try {
                img2 = Transformacao.filtroLaplaciano(img, 1);
                attImagem2();
                attCodigo(51);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:   FILTRO LAPLACIANO2
        if (img != null) {
            try {
                img2 = Transformacao.filtroLaplaciano(img, 2);
                attImagem2();
                attCodigo(52);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here: FILTRO DA MEDIA
        if (img != null) {
            try {
                img2 = Transformacao.filtroMedia(img, Integer.valueOf(JOptionPane.showInputDialog("valor do N (mascara NxN): ")));
                attImagem2();
                attCodigo(6);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:    REPLICACAO
        if (img != null) {
            try {
                img2 = Transformacao.replicacao(img, Integer.valueOf(JOptionPane.showInputDialog("Aumentar Quantas Vezes: ")));
                attImagem2();
                attCodigo(71);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.redução(img, Integer.valueOf(JOptionPane.showInputDialog("Aumentar Quantas Vezes: ")));
                attImagem2();
                attCodigo(72);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:  GRAVA EM UM ARQUIVO, NO MESMO DIRETORIO, O HISTOGRAMA DA IMAGEM EM QUESTAO
        if (img != null) {
            try {
                img.gravarHistograma();
                String nome = img.getFile().getName();
                nome = nome.substring(0, nome.lastIndexOf('.'));
                JOptionPane.showMessageDialog(this, "Histograma Salvo no mesmo diretorio da imagem com o Nome:\n\"" + nome + " Histograma.txt\"");
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here: EQUALIZACAO POR HISTOGRAMA
        if (img != null) {
            try {
                img2 = Transformacao.equalizacaoHistograma(img);
                attImagem2();
                attCodigo(8);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.equalizacaoLocal(img, Integer.valueOf(JOptionPane.showInputDialog("Tamanho,N, da Mascara NxN: ")));
                attImagem2();
                attCodigo(9);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
//                img2 = Transformacao.estatisticaDHistograma(img, (float) 2.6, (float) 0.4, (float) 0.005, (float) 0.6, Integer.valueOf(JOptionPane.showInputDialog("Tamanho,N, da Mascara NxN: ")));
                img2 = Transformacao.estatisticaDHistograma(img, (float) 4.0, (float) 0.4, (float) 0.02, (float) 0.4, Integer.valueOf(JOptionPane.showInputDialog("Tamanho,N, da Mascara NxN: ")));
                attImagem2();
                attCodigo(10);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:  SOMA DUAS IMAGENS
        if (img != null) {
            try {
                if (img2 != null) {
                    img2 = Transformacao.somarIMG(img, img2);
                    attImagem2();
                    attCodigo(11);
                } else if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    String arq = jFileChooser1.getSelectedFile().getName();
                    String ext = arq.substring(arq.lastIndexOf('.'));
                    if (ext.equals(".pgm") || ext.equals(".pbm") || ext.equals(".ppm")) {
                        Imagem img3 = new Imagem();
                        img3.carregaImagem(jFileChooser1.getSelectedFile());
                        img2 = Transformacao.somarIMG(img, img3);
                        attImagem2();
                        attCodigo(11);
                    }
                }
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                if (img2 != null) {
                    img2 = Transformacao.SubtrairIMG(img, img2);
                    attImagem2();
                    attCodigo(12);
                } else if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    String arq = jFileChooser1.getSelectedFile().getName();
                    String ext = arq.substring(arq.lastIndexOf('.'));
                    if (ext.equals(".pgm") || ext.equals(".pbm") || ext.equals(".ppm")) {
                        Imagem img3 = new Imagem();
                        img3.carregaImagem(jFileChooser1.getSelectedFile());
                        img2 = Transformacao.SubtrairIMG(img, img3);
                        attImagem2();
                        attCodigo(12);
                    }
                }
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.gama(img, Float.valueOf(JOptionPane.showInputDialog("Valor do Gama: ")));
                attImagem2();
                attCodigo(13);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.AumentarCor(img, 1, Integer.valueOf(JOptionPane.showInputDialog("valor Somado: ")));
                attImagem2();
                attCodigo(14);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.DiminuirCor(img, 1, Integer.valueOf(JOptionPane.showInputDialog("valor Somado: ")));
                attImagem2();
                attCodigo(15);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            img2 = Transformacao.ExtrairCanalHSI(img, 0);
            attImagem2();
            attCodigo(163);
        }
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.AumentarCor(img, 0, Integer.valueOf(JOptionPane.showInputDialog("valor Somado: ")));
                attImagem2();
                attCodigo(14);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.AumentarCor(img, 2, Integer.valueOf(JOptionPane.showInputDialog("valor Somado: ")));
                attCodigo(14);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.DiminuirCor(img, 0, Integer.valueOf(JOptionPane.showInputDialog("valor Somado: ")));
                attImagem2();
                attCodigo(15);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.DiminuirCor(img, 2, Integer.valueOf(JOptionPane.showInputDialog("valor Somado: ")));
                attImagem2();
                attCodigo(15);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
        if (img != null) { // RBG           
            try {
                img2 = Transformacao.misturarCanais(img, 0, 2, 1);
                attImagem2();
                attCodigo(17);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
        if (img != null) { // GRB            
            try {
                img2 = Transformacao.misturarCanais(img, 1, 0, 2);
                attImagem2();
                attCodigo(17);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        // TODO add your handling code here:
        if (img != null) {//GBR            
            try {
                img2 = Transformacao.misturarCanais(img, 1, 2, 0);
                attImagem2();
                attCodigo(17);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        // TODO add your handling code here:
        if (img != null) { // BRG
            try {
                img2 = Transformacao.misturarCanais(img, 2, 0, 1);
                attImagem2();
                attCodigo(17);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        // TODO add your handling code here:
        if (img != null) { // BGR            
            try {
                img2 = Transformacao.misturarCanais(img, 2, 1, 0);
                attImagem2();
                attCodigo(17);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalHSI(img, 1);
                attImagem2();
                attCodigo(163);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalHSI(img, 2);
                attImagem2();
                attCodigo(163);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalCMY(img, 0);
                attImagem2();
                attCodigo(162);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalCMY(img, 1);
                attImagem2();
                attCodigo(162);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalCMY(img, 2);
                attImagem2();
                attCodigo(162);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalRGB(img, 0);
                attImagem2();
                attCodigo(161);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalRGB(img, 1);
                attImagem2();
                attCodigo(161);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ExtrairCanalRGB(img, 2);
                attImagem2();
                attCodigo(161);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        // TODO add your handling code here:
        if (img != null) { // BGR            
            try {
                img2 = Transformacao.misturarCanais(img, 0, 1, 2);
                attImagem2();
                attCodigo(17);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        // TODO add your handling code here:        
        if (img != null) {
            try {
                img2 = Transformacao.negativo(img);
                attImagem2();
                attCodigo(19);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }

    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            if (jFileChooser1.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                img.salvarComo(jFileChooser1.getSelectedFile());
            }
        }
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ClarearSoma(img, Integer.valueOf(JOptionPane.showInputDialog("Somar Quanto? ")));
                attImagem2();
                attCodigo(71);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.ClarearMultp(img, Float.valueOf(JOptionPane.showInputDialog("Multiplicar por Quanto? ")));
                attImagem2();
                attCodigo(71);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.EscurecerSub(img, Integer.valueOf(JOptionPane.showInputDialog("Subtrair Quanto? ")));
                attImagem2();
                attCodigo(71);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.EscurecerDiv(img, Float.valueOf(JOptionPane.showInputDialog("Dividir por Quanto? ")));
                attImagem2();
                attCodigo(71);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem48ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Agora voce vai abrir 3 imagens .PGM.\n "
                + "A primeira referente ao canal RED, a segundo ao GREEN e a terceira ao BLUE", "Continuar?",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            try {
                Imagem img3 = null;
                if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    img = new Imagem();
                    img.carregaImagem(jFileChooser1.getSelectedFile());
                }
                if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    img2 = new Imagem();
                    img2.carregaImagem(jFileChooser1.getSelectedFile());
                }
                if (jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                    img3 = new Imagem();
                    img3.carregaImagem(jFileChooser1.getSelectedFile());
                }
                img = Transformacao.juntarCanaisRGB(img, img2, img3);
                attImagem();
                attCodigo(71);
            } catch (Exception e) {
                System.out.println("ERRRO -" + e);
            }
        }
    }//GEN-LAST:event_jMenuItem48ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   <<<<<
        if (img2 != null) {
            if (a == 1) {
                jToggleButton1ActionPerformed(evt);
            }
            try {
                img = img2;
                img2 = null;
                attImagem();
                attImagem2();
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (img2 != null) {
            try {
                if (a == 0) {
                    a = 1;
                    jmodelv = jScrollPane1.getVerticalScrollBar().getModel();
                    jmodelh = jScrollPane1.getHorizontalScrollBar().getModel();

                    jScrollPane1.getVerticalScrollBar().setModel(jScrollPane2.getVerticalScrollBar().getModel());
                    jScrollPane1.getHorizontalScrollBar().setModel(jScrollPane2.getHorizontalScrollBar().getModel());

                } else {
                    a = 0;
                    jScrollPane1.getVerticalScrollBar().setModel(jmodelv);
                    jScrollPane1.getHorizontalScrollBar().setModel(jmodelh);
                }
                attImagem2();
                attImagem();
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49ActionPerformed
        // TODO add your handling code here:
//        if (img != null) {
//            try {
//                int qCores = Integer.valueOf(JOptionPane.showInputDialog("Quantas Cores? "));
//                if (qCores < 2) {
//                    return;
//                }
//                int[] limites = new int[qCores + 1];
//                Color[] cores = new Color[qCores];
//                limites[0] = 0;
//                limites[limites.length - 1] = 255;
//                JColorChooser jcc = new JColorChooser();
//                cores[0] = jcc.showDialog(jcc, "Primeira Cor", Color.BLACK);
//                for (int i = 1; i < limites.length - 1; i++) {
//                    limites[i] = Integer.valueOf(JOptionPane.showInputDialog("Defina o Limite de numero " + (i) + " ? "));
//                    cores[i] = jcc.showDialog(jcc, "Cor do limite " + (i) + ": ", Color.BLACK);
//                }
//                img2 = Transformacao.pseudoCores(img, cores, limites);
//                attImagem2();
//                attCodigo(18);
//            } catch (Exception e) {
//                System.out.println("ERRRO -" + e);
//            }
//        }

    img = Transformacao.H();
    attImagem();

    }//GEN-LAST:event_jMenuItem49ActionPerformed

    private void jMenuItem50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem50ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.filtroLaplaciano(img, 3);
                attImagem2();
                attCodigo(52);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem50ActionPerformed

    private void jMenuItem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem51ActionPerformed
        // TODO add your handling code here:
        if (img != null) {
            try {
                img2 = Transformacao.filtroLaplaciano(img, 4);
                attImagem2();
                attCodigo(52);
            } catch (Exception e) {
                System.out.println("ERRO");
            }
        }
    }//GEN-LAST:event_jMenuItem51ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private Imagem img = null;
    private Imagem img2 = null;
    private int a = 0;
    private BoundedRangeModel jmodelv = null;
    private BoundedRangeModel jmodelh = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextPane jtp;
    // End of variables declaration//GEN-END:variables

    void attImagem() {
        if (img != null) {
            img.gerarImagem();
            if (img.getImage() != null) {
                jLabel1.setIcon(new ImageIcon(img.getImage()));

            }
        }
    }

    void attImagem2() {
        if (img2 != null) {
            img2.gerarImagem();
            if (img2.getImage() != null) {
                jLabel2.setIcon(new ImageIcon(img2.getImage()));

            }
        } else {
            jLabel2.setIcon(null);
            jLabel2.repaint();
        }
    }

    void attCodigo(int cod) {
        String im = "";
        String c;
        HelpText ht = new HelpText();
        String t = "";
        switch (cod) {
            case 0:
                im = "/imagens/codigos/0.CarregarImagem.PNG";

                break;
            case 1:
                im = "/imagens/codigos/1.Binarizacao.PNG";
                break;
            case 2:
                c = img.getT() == 1 ? "PBM" : img.getT() == 2 ? "PGM" : "PPM";
                im = "/imagens/codigos/2.Espelhar" + c + ".png";
                break;
            case 3:
                c = img.getT() == 1 ? "PBM" : img.getT() == 2 ? "PGM" : "PPM";
                im = "/imagens/codigos/3.Rotacionar90Direita" + c + ".png";
                break;
            case 4:
                c = img.getT() == 1 ? "PBM" : img.getT() == 2 ? "PGM" : "PPM";
                im = "/imagens/codigos/4.Rotacionar90Esquerda" + c + ".png";
                break;
            case 51:
            case 52:
            case 53:
            case 54:
                String a = img.getT() == 2 ? "PGM" : img.getT() == 3 ? "PPM" : "";
                String b = "" + (cod - 50);
                im = "/imagens/codigos/5.Laplaciano" + b + a + ".png";
                break;
            case 6:
                im = "/imagens/codigos/6.filtrodaMedia.png";
                break;
            case 71:
                c = img.getT() == 3 ? "PPM" : img.getT() == 2 ? "PGM" : "";
                im = "/imagens/codigos/7.REPLICACAO" + c + ".png";
                break;
            case 72:
                c = img.getT() == 3 ? "PPM" : img.getT() == 2 ? "PGM" : "";
                im = "/imagens/codigos/7.Reducao" + c + ".png";
                break;
            case 8:
                im = "/imagens/codigos/8.EqualizacaoHistograma.png";
                break;
            case 9:
                im = "/imagens/codigos/9.EqualizacaoLocal.png";
                break;
            case 10:
                im = "/imagens/codigos/10.estatisticaDHistograma.png";
                break;
            case 11:
                c = img.getT() == 3 ? "PPM" : img.getT() == 2 ? "PGM" : "";
                im = "/imagens/codigos/11.SomaIMG" + c + ".png";
                break;
            case 12:
                c = img.getT() == 3 ? "PPM" : img.getT() == 2 ? "PGM" : "";
                im = "/imagens/codigos/11.SubtrairIMG" + c + ".png";
                break;
            case 13:
                c = img.getT() == 3 ? "PPM" : img.getT() == 2 ? "PGM" : "";
                im = "/imagens/codigos/13.Gama" + c + ".png";
                break;
            case 14:
                im = "/imagens/codigos/14.aumentarCorRGB.png";
                break;
            case 15:
                im = "/imagens/codigos/14.diminuirCorRGB.png";
                break;
            case 161:
                im = "/imagens/codigos/16.ExtrairCanalRGB.png";
                break;
            case 162:
                im = "/imagens/codigos/16.ExtrairCanalCMY.png";
                break;
            case 163:
                im = "/imagens/codigos/16.ExtrairCanalHSI.png";
                break;
            case 17:
                im = "/imagens/codigos/17.MisturarCanaisRGB.png";
                break;
            case 18:
                im = "/imagens/codigos/18.PseudoCores.png";
                break;
            case 19:
                im = "/imagens/codigos/19.Negativo.png";
                break;
            case 21:
                im = "/imagens/codigos/21.ClarearSoma.png";
                break;
            case 211:
                im = "/imagens/codigos/211.ClarearMultp.png";
                break;
            case 22:
                im = "/imagens/codigos/22.EscurecerSub.png";
                break;
            case 221:
                im = "/imagens/codigos/221.EscurecerDiv.png";
                break;
            default:
                im = "";
                break;

        }
        jtp.setText(ht.text(cod));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(im)));
    }

}
